# Spring properties
spring:
  jpa:
    show-sql: true
    hibernate:
      default_schema: public
      ddl-auto: update
    properties:
      hibernate:
        order_inserts: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
          lob:
            non_contextual_creation: false
        temp:
          use_jdbc_metadata_defaults: false

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://ec2-52-23-14-156.compute-1.amazonaws.com:5432/ddoodid1gjn1cg
    driver-class-name: org.postgresql.Driver
    username: ytmfblnjfrinua
    password: c19b0e0d515d0e68bbb04b65853516a8cb906294cd11aefb114f1c1816c196ec
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 5

logging:
  level:
    root: INFO
    org.springframework: ERROR


